# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/source.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'protos/source.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13protos/source.proto\x12\x06source\"V\n\rSourceRequest\x12\x0b\n\x03url\x18\x01 \x01(\t\x12\x19\n\x11\x63ontainsAiContent\x18\x02 \x01(\x08\x12\x1d\n\x15\x63ontainsAfricaContent\x18\x03 \x01(\x08\"!\n\x0eSourceResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x0f\n\rScrapeRequest\"!\n\x0eScrapeResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2\x88\x01\n\rSourceService\x12<\n\taddSource\x12\x15.source.SourceRequest\x1a\x16.source.SourceResponse\"\x00\x12\x39\n\x06scrape\x12\x15.source.ScrapeRequest\x1a\x16.source.ScrapeResponse\"\x00\x42\rB\x0bSourceProtob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.source_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'B\013SourceProto'
  _globals['_SOURCEREQUEST']._serialized_start=31
  _globals['_SOURCEREQUEST']._serialized_end=117
  _globals['_SOURCERESPONSE']._serialized_start=119
  _globals['_SOURCERESPONSE']._serialized_end=152
  _globals['_SCRAPEREQUEST']._serialized_start=154
  _globals['_SCRAPEREQUEST']._serialized_end=169
  _globals['_SCRAPERESPONSE']._serialized_start=171
  _globals['_SCRAPERESPONSE']._serialized_end=204
  _globals['_SOURCESERVICE']._serialized_start=207
  _globals['_SOURCESERVICE']._serialized_end=343
# @@protoc_insertion_point(module_scope)
